name: CI

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # allows you to run this workflow manually from Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  CI: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node JS
      - uses: actions/setup-node@v3.8.1
        with: 
          node-version: 18.16.0
